#!/bin/bash

cd "$( dirname "${BASH_SOURCE[0]}" )"

if [ $# -eq 0 ]
then
	echo "No wallpaper program specified. Selecting random program."
	choice=$(shuf -n 1 -i 1-9)
	case $choice in
	1)
		./wp-gen landscape
		;;
	2)
		./wp-gen islands
		;;
	3)
		./wp-gen clouds
		;;
	4)
		./wp-gen tangles
		;;
	5)
		./wp-gen marrowlike
		;;
	6)
		./wp-gen mesh
		;;
	7)
		./wp-gen fern
		;;
	8)
		./wp-gen lightning
		;;
	9)
		./wp-gen zebra
		;;
	esac
else
	if [ "$1" == "clean" ]
	then
		rm -r out/*.o
	else
		echo "Generating wallpaper with program '$1'."
		mkdir -p out
		cd out
		[ -f "$1".o ] && [ $(date +%s%N -r ../"$1".c) -lt $(date +%s%N -r "$1".o) ] \
				|| gcc -s -Ofast -lm ../"$1".c -o "$1".o
		./"$1".o wallpaper.ppm
		convert wallpaper.ppm wallpaper.jpg
	fi
fi
